# Base configs
baseurl: "https://jonasdeluna.github.io/photography/"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photo Gallery"
subtitle: ""
author: "Jonas de Luna Skulberg"
header:
 title: "Gallery"
 subtitle: ""
footer:
 name: ""
 bio: ""
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/rampatra/photography\">fork this repo on github</a> ;)"
web_design: "AJ"

social_urls:
  github: "https://www.github.com/jonasdeluna"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}, {"tag": "FocalLength", "icon": "fa fa-ruler"}]'